/**
 * Playoff Configurations Schema
 *
 * Stores playoff bracket configurations at three levels:
 * - Global: System-provided templates (read-only for operators)
 * - Organization: Org-level defaults that apply to all leagues
 * - League: League-specific overrides
 *
 * Key design principles:
 * 1. Store SETTINGS, not actual matchups
 * 2. Templates (seeded/ranked/random/bracket) are algorithms, not stored data
 * 3. Given the same settings + standings, the same matchups are always generated
 * 4. Hierarchy: league -> organization -> global (fallback chain)
 *
 * The configuration is flexible enough to work with any team count because:
 * - Qualification settings (all/fixed/percentage) scale with league size
 * - Matchup templates use seed references (1st, 2nd, 3rd...) not actual team IDs
 * - When applied to a specific season, the system:
 *   a) Calculates bracket size from qualification rules + team count
 *   b) Generates matchup pairs using generateMatchupPairs(bracketSize, style)
 *   c) Maps seeds to actual teams based on standings
 *   d) Creates match records with real team assignments
 *
 * The matchup generation logic lives in:
 *   src/hooks/playoff/usePlayoffSettingsReducer.ts
 *   - generateMatchupPairs(bracketSize, style) → Array<[homeSeed, awaySeed]>
 *   - calculateQualifyingTeams(totalTeams, settings) → number
 *
 * Global Entity ID:
 *   The nil UUID '00000000-0000-0000-0000-000000000000' is used for global templates.
 *   This UUID cannot be generated by UUID v4 generators (RFC 4122), ensuring no collision.
 */

-- ============================================================================
-- CONSTANTS
-- ============================================================================
-- Global/System entity ID (nil UUID - cannot be generated by UUID v4)
-- Use this for entity_id when entity_type = 'global'
-- In TypeScript: export const GLOBAL_ENTITY_ID = '00000000-0000-0000-0000-000000000000';

-- ============================================================================
-- PLAYOFF CONFIGURATIONS TABLE
-- ============================================================================
CREATE TABLE playoff_configurations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- === Entity Ownership ===
    -- Determines the scope/level of this configuration
    entity_type TEXT NOT NULL CHECK (entity_type IN ('global', 'organization', 'league')),

    -- The entity this configuration belongs to:
    -- - global: '00000000-0000-0000-0000-000000000000' (nil UUID)
    -- - organization: the organization's UUID
    -- - league: the league's UUID
    entity_id UUID NOT NULL,

    -- === Configuration Metadata ===
    name TEXT NOT NULL,                          -- e.g., "Standard 4-Team Bracket", "Double Elimination"
    description TEXT,                            -- Optional description of what this configuration does

    -- Is this the default config for this entity?
    -- For global: marks the recommended default template
    -- For organization: the org's default for new leagues
    -- For league: not used (league only has one config)
    is_default BOOLEAN DEFAULT false,

    -- === Qualification Settings ===
    -- These determine how many teams make it into the bracket

    qualification_type TEXT NOT NULL DEFAULT 'all'
        CHECK (qualification_type IN ('all', 'fixed', 'percentage')),

    -- For 'fixed' type: exactly this many teams qualify
    fixed_team_count INTEGER DEFAULT 4 CHECK (fixed_team_count >= 2),

    -- For 'percentage' type: this percentage of teams qualify
    qualifying_percentage INTEGER DEFAULT 50 CHECK (qualifying_percentage BETWEEN 1 AND 100),
    percentage_min INTEGER DEFAULT 4 CHECK (percentage_min >= 2),  -- Minimum teams even if % is lower
    percentage_max INTEGER DEFAULT NULL,                           -- Maximum cap (NULL = no limit)

    -- === Playoff Structure ===

    playoff_weeks INTEGER NOT NULL DEFAULT 1 CHECK (playoff_weeks >= 1),

    -- Matchup style for each week (array index = week number - 1)
    -- Valid values: 'seeded', 'ranked', 'random', 'bracket'
    -- Week 1 typically 'seeded', subsequent weeks typically 'bracket'
    week_matchup_styles TEXT[] NOT NULL DEFAULT ARRAY['seeded']::TEXT[],

    -- Wildcard spots replace the last N bracket positions with random selection
    -- 0 = disabled, all spots determined by standings
    wildcard_spots INTEGER NOT NULL DEFAULT 0 CHECK (wildcard_spots >= 0),

    -- Payment method for additional playoff weeks
    payment_method TEXT NOT NULL DEFAULT 'automatic'
        CHECK (payment_method IN ('automatic', 'manual')),

    -- === Generation Control ===

    -- When true: System automatically creates playoff matches when regular season ends
    -- When false: Operator must manually trigger playoff generation from the league page
    -- Defaults to false so new operators can verify the system works as expected first
    auto_generate BOOLEAN NOT NULL DEFAULT false,

    -- === Timestamps ===
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- === Constraints ===
    -- Ensure global records use the nil UUID
    CONSTRAINT valid_global_entity CHECK (
        (entity_type = 'global' AND entity_id = '00000000-0000-0000-0000-000000000000') OR
        (entity_type != 'global' AND entity_id != '00000000-0000-0000-0000-000000000000')
    ),

    -- Each entity can only have one config with a given name
    CONSTRAINT unique_entity_config_name UNIQUE (entity_type, entity_id, name)
);

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Fast lookup by entity
CREATE INDEX idx_playoff_configurations_entity
    ON playoff_configurations(entity_type, entity_id);

-- Find global templates quickly
CREATE INDEX idx_playoff_configurations_global
    ON playoff_configurations(entity_type)
    WHERE entity_type = 'global';

-- Find default config for an entity
CREATE INDEX idx_playoff_configurations_default
    ON playoff_configurations(entity_type, entity_id)
    WHERE is_default = true;


-- ============================================================================
-- EXAMPLE: How configurations work at each level
-- ============================================================================
/*
Global Templates (entity_type = 'global', entity_id = '00000000-0000-0000-0000-000000000000'):
- Created by developers, read-only for operators
- Shown in template picker on org/league settings pages
- Examples: "Standard Single Elimination", "Double Elimination"

Organization Configs (entity_type = 'organization', entity_id = org_uuid):
- Created by operators for their organization
- Serves as default for all leagues in that org
- Can be based on a global template or custom

League Configs (entity_type = 'league', entity_id = league_uuid):
- Created when a league needs different settings than org default
- Overrides organization settings for this specific league

Example flow:
1. Operator views playoff settings for their org
2. Sees global templates: "Standard" and "Double Elimination"
3. Selects "Standard" as their org default
4. Creates a league - it inherits the org default
5. Later, customizes one league to use different settings
*/


-- ============================================================================
-- HELPER FUNCTION: Decode seed for display
-- ============================================================================

-- Function to decode a seed value into human-readable format
-- Seed encoding (from generateMatchupPairs):
--   1-99: Regular seeds (1st place, 2nd place, etc.)
--   100-199: Winner of match N (e.g., 101 = Winner of Match 1)
--   200-299: Loser of match N (e.g., 201 = Loser of Match 1)
--   Negative: Random selection indicator
CREATE OR REPLACE FUNCTION decode_playoff_seed(seed INTEGER)
RETURNS TEXT AS $$
BEGIN
    IF seed < 0 THEN
        RETURN 'Random Team';
    ELSIF seed >= 200 AND seed < 300 THEN
        RETURN 'Loser Match ' || (seed - 200);
    ELSIF seed >= 100 AND seed < 200 THEN
        RETURN 'Winner Match ' || (seed - 100);
    ELSE
        RETURN seed || CASE
            WHEN seed % 100 IN (11, 12, 13) THEN 'th'
            WHEN seed % 10 = 1 THEN 'st'
            WHEN seed % 10 = 2 THEN 'nd'
            WHEN seed % 10 = 3 THEN 'rd'
            ELSE 'th'
        END || ' Place';
    END IF;
END;
$$ LANGUAGE plpgsql IMMUTABLE;


-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE playoff_configurations ENABLE ROW LEVEL SECURITY;

-- Everyone can read global templates
CREATE POLICY "Anyone can view global templates"
    ON playoff_configurations
    FOR SELECT
    USING (entity_type = 'global');

-- Organization staff can read their org's configs
CREATE POLICY "Org staff can view org playoff configurations"
    ON playoff_configurations
    FOR SELECT
    USING (
        entity_type = 'organization' AND
        entity_id IN (
            SELECT organization_id FROM organization_staff
            WHERE member_id IN (
                SELECT id FROM members WHERE user_id = auth.uid()
            )
        )
    );

-- Organization staff can manage their org's configs (but not global)
CREATE POLICY "Org staff can manage org playoff configurations"
    ON playoff_configurations
    FOR ALL
    USING (
        entity_type = 'organization' AND
        entity_id IN (
            SELECT organization_id FROM organization_staff
            WHERE member_id IN (
                SELECT id FROM members WHERE user_id = auth.uid()
            )
        )
    );

-- Organization staff can view their leagues' configs
CREATE POLICY "Org staff can view league playoff configurations"
    ON playoff_configurations
    FOR SELECT
    USING (
        entity_type = 'league' AND
        entity_id IN (
            SELECT l.id FROM leagues l
            JOIN organization_staff os ON l.organization_id = os.organization_id
            JOIN members m ON os.member_id = m.id
            WHERE m.user_id = auth.uid()
        )
    );

-- Organization staff can manage their leagues' configs
CREATE POLICY "Org staff can manage league playoff configurations"
    ON playoff_configurations
    FOR ALL
    USING (
        entity_type = 'league' AND
        entity_id IN (
            SELECT l.id FROM leagues l
            JOIN organization_staff os ON l.organization_id = os.organization_id
            JOIN members m ON os.member_id = m.id
            WHERE m.user_id = auth.uid()
        )
    );


-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Update timestamps
CREATE TRIGGER update_playoff_configurations_updated_at
    BEFORE UPDATE ON playoff_configurations
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Ensure only one default per entity
CREATE OR REPLACE FUNCTION ensure_single_default_playoff_config()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.is_default = true THEN
        UPDATE playoff_configurations
        SET is_default = false
        WHERE entity_type = NEW.entity_type
          AND entity_id = NEW.entity_id
          AND id != NEW.id
          AND is_default = true;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_ensure_single_default_playoff_config
    BEFORE INSERT OR UPDATE ON playoff_configurations
    FOR EACH ROW
    EXECUTE FUNCTION ensure_single_default_playoff_config();


-- ============================================================================
-- SEED DATA: Global Templates
-- ============================================================================
/*
INSERT INTO playoff_configurations (
    entity_type,
    entity_id,
    name,
    description,
    is_default,
    qualification_type,
    fixed_team_count,
    playoff_weeks,
    week_matchup_styles,
    wildcard_spots,
    auto_generate
) VALUES
-- Standard Single Elimination (default global template)
(
    'global',
    '00000000-0000-0000-0000-000000000000',
    'Standard Single Elimination',
    'Classic playoff format where top teams are seeded against bottom teams. Winners advance, losers are eliminated. Best for leagues wanting a quick, decisive playoff.',
    true,
    'fixed',
    4,
    2,
    ARRAY['seeded', 'bracket']::TEXT[],
    0,
    false
),
-- Double Elimination
(
    'global',
    '00000000-0000-0000-0000-000000000000',
    'Double Elimination',
    'Teams must lose twice to be eliminated. First week pairs winners vs winners and losers vs losers. Gives teams a second chance while still rewarding top performers.',
    false,
    'fixed',
    4,
    2,
    ARRAY['seeded', 'bracket']::TEXT[],
    0,
    false
);
*/
