/**
 * @fileoverview Schedule-related type definitions
 *
 * Types for team schedule positions, matches, and schedule generation.
 * Used for creating and managing league schedules with matchup assignments.
 */

import type { SeasonWeek } from './season';

/**
 * Match status types
 */
export type MatchStatus =
  | 'scheduled'             // Not yet played
  | 'in_progress'           // Currently being played
  | 'awaiting_verification' // Scored but needs both teams to verify
  | 'completed'             // Finished and verified
  | 'forfeited'             // One team forfeited
  | 'postponed';            // Rescheduled to different date

/**
 * Team schedule position assignment
 * Maps teams to positions (1-N) used in matchup tables
 */
export interface TeamSchedulePosition {
  id: string;
  season_id: string;
  team_id: string;
  schedule_position: number;  // 1-N position in matchup table
  created_at: string;
  updated_at: string;
}

/**
 * Team schedule position insert data
 * Uses Omit<> to exclude auto-generated fields
 * This automatically stays in sync when TeamSchedulePosition type changes
 */
export type TeamSchedulePositionInsertData = Omit<TeamSchedulePosition,
  | 'id'          // Auto-generated by database
  | 'created_at'  // Auto-generated timestamp
  | 'updated_at'  // Auto-generated timestamp
>;

/**
 * Match record - weekly matchup between two teams
 */
export interface Match {
  id: string;
  season_id: string;
  season_week_id: string;       // FK to season_weeks table
  home_team_id: string | null;  // Null if BYE
  away_team_id: string | null;  // Null if BYE
  scheduled_venue_id: string | null;  // Home team's venue by default
  actual_venue_id: string | null;     // If venue changed from scheduled (overflow)
  assigned_table_number: number | null; // Table number assigned at the venue
  match_number: number;          // Order on the night (1, 2, 3...)
  status: MatchStatus;

  // Score tracking (nullable until completed)
  home_team_score: number | null;
  away_team_score: number | null;

  // Detailed results tracking (added for end-of-match verification)
  home_games_won: number | null;
  away_games_won: number | null;
  home_points_earned: number | null;
  away_points_earned: number | null;
  home_games_to_win: number | null;
  home_games_to_tie: number | null;
  away_games_to_win: number | null;
  away_games_to_tie: number | null;

  created_at: string;
  updated_at: string;
}

/**
 * Match insert data
 * Uses Omit<> to exclude auto-generated fields and nullable score fields
 * This automatically stays in sync when Match type changes
 */
export type MatchInsertData = Omit<Match,
  | 'id'                     // Auto-generated by database
  | 'actual_venue_id'        // Set later if venue changes (overflow)
  | 'assigned_table_number'  // Assigned by trigger/function
  | 'home_team_score'        // Filled during match scoring
  | 'away_team_score'        // Filled during match scoring
  | 'home_games_won'         // Filled during match scoring
  | 'away_games_won'         // Filled during match scoring
  | 'home_points_earned'     // Filled during match scoring
  | 'away_points_earned'     // Filled during match scoring
  | 'home_games_to_win'      // Filled during match scoring
  | 'home_games_to_tie'      // Filled during match scoring
  | 'away_games_to_win'      // Filled during match scoring
  | 'away_games_to_tie'      // Filled during match scoring
  | 'created_at'             // Auto-generated timestamp
  | 'updated_at'             // Auto-generated timestamp
>;

/**
 * Match with expanded team and venue details
 * Used for displaying match information
 */
export interface MatchWithDetails extends Match {
  scheduled_date?: string;  // Denormalized from season_week for easier access
  home_team?: {
    id: string;
    team_name: string;
    captain_id: string;
  } | null;
  away_team?: {
    id: string;
    team_name: string;
    captain_id: string;
  } | null;
  scheduled_venue?: {
    id: string;
    name: string;
    street_address?: string;
    city: string;
    state: string;
  } | null;
  actual_venue?: {
    id: string;
    name: string;
    street_address?: string;
    city: string;
    state: string;
  } | null;
  season_week?: {
    id: string;
    scheduled_date: string;
    week_name: string;
    week_type: string;
  } | null;
}

/**
 * Matchup pair from matchup tables
 * Array of [position1, position2] representing which teams play
 */
export type MatchupPair = [number, number];

/**
 * Weekly matchup structure from matchup tables (legacy format)
 * @deprecated Use optimized format (MatchupPair[][]) for new schedules
 */
export interface WeeklyMatchup {
  week: number;
  matches: MatchupPair[];
}

/**
 * Matchup table type - array of weeks, each containing match pairs
 * Week number = array index + 1
 */
export type MatchupTable = MatchupPair[][];

/**
 * Team with assigned schedule position
 * Used during schedule generation
 */
export interface TeamWithPosition {
  id: string;
  team_name: string;
  home_venue_id: string | null;
  schedule_position: number;
}

/**
 * Note: SeasonWeek is imported from season.ts (see top of file)
 * This avoids type duplication - the complete definition is in season.ts
 */

/**
 * Extended match details with venue location
 */
export interface MatchWithVenueDetails extends MatchWithDetails {
  scheduled_venue?: {
    id: string;
    name: string;
    street_address: string;
    city: string;
    state: string;
  } | null;
}

/**
 * Week schedule data - week with all its matches
 */
export interface WeekSchedule {
  week: SeasonWeek;
  matches: MatchWithDetails[];
}
