/**
 * @fileoverview Team-related type definitions
 * Types for teams, rosters, and player management
 */

/**
 * Team status types
 */
export type TeamStatus = 'active' | 'withdrawn' | 'forfeited';

/**
 * Team player status types
 */
export type TeamPlayerStatus = 'active' | 'inactive' | 'dropped';

/**
 * Team database record interface
 * Represents a team competing in a specific season
 */
export interface Team {
  id: string;
  season_id: string;
  league_id: string;
  captain_id: string;
  home_venue_id: string | null;
  team_name: string;
  roster_size: number; // 5 or 8
  wins: number;
  losses: number;
  ties: number;
  points: number;
  games_won: number;
  games_lost: number;
  status: TeamStatus;
  created_at: string;
  updated_at: string;
}

/**
 * Team insert data (for creating new teams)
 * Uses Omit<> to exclude auto-generated fields and calculated stats
 * This automatically stays in sync when Team type changes
 */
export type TeamInsertData = Omit<Team,
  | 'id'           // Auto-generated by database
  | 'wins'         // Calculated from match results
  | 'losses'       // Calculated from match results
  | 'ties'         // Calculated from match results
  | 'points'       // Calculated from match results
  | 'games_won'    // Calculated from match results
  | 'games_lost'   // Calculated from match results
  | 'status'       // Has default value in database
  | 'created_at'   // Auto-generated timestamp
  | 'updated_at'   // Auto-generated timestamp
>;

/**
 * Team player (roster member) database record
 * Links a player to a team for a specific season
 */
export interface TeamPlayer {
  id: string;
  team_id: string;
  member_id: string;
  season_id: string;
  is_captain: boolean;
  individual_wins: number;
  individual_losses: number;
  skill_level: number | null; // BCA skill level 1-9
  status: TeamPlayerStatus;
  joined_at: string;
  updated_at: string;
}

/**
 * Team player insert data (for adding players to roster)
 * Uses Omit<> to exclude auto-generated fields and calculated stats
 * This automatically stays in sync when TeamPlayer type changes
 */
export type TeamPlayerInsertData = Omit<TeamPlayer,
  | 'id'                  // Auto-generated by database
  | 'individual_wins'     // Calculated from match results
  | 'individual_losses'   // Calculated from match results
  | 'status'              // Has default value in database
  | 'joined_at'           // Auto-generated timestamp
  | 'updated_at'          // Auto-generated timestamp
>;

/**
 * Team with expanded data for display
 * Includes captain info and venue name
 */
export interface TeamWithDetails extends Team {
  captain_name?: string;
  captain_email?: string;
  venue_name?: string;
  player_count?: number;
}

/**
 * Team with full nested query data from Supabase
 * Used when querying teams with captain, roster, and venue details
 */
export interface TeamWithQueryDetails extends Team {
  captain?: {
    id: string;
    first_name: string;
    last_name: string;
    phone: string;
    email: string;
    system_player_number: number;
    bca_member_number: string | null;
  };
  team_players?: Array<{
    count?: number;
    member_id?: string;
    is_captain?: boolean;
    members?: {
      id: string;
      first_name: string;
      last_name: string;
      system_player_number: number;
      bca_member_number: string | null;
    };
  }>;
  venue?: {
    id: string;
    name: string;
    phone?: string;
    street_address?: string;
    city?: string;
    state?: string;
  };
}

/**
 * Utility function to format team record for display
 */
export function formatTeamRecord(team: Team): string {
  if (team.wins === 0 && team.losses === 0 && team.ties === 0) {
    return '0-0';
  }
  if (team.ties > 0) {
    return `${team.wins}-${team.losses}-${team.ties}`;
  }
  return `${team.wins}-${team.losses}`;
}

/**
 * Utility function to calculate win percentage
 */
export function calculateWinPercentage(team: Team): number {
  const totalGames = team.wins + team.losses;
  if (totalGames === 0) return 0;
  return Math.round((team.wins / totalGames) * 100);
}

/**
 * Return type for useTeamManagement hook
 * Provides all team management data and control functions
 */
export interface UseTeamManagementReturn {
  league: import('./league').League | null;
  venues: import('./venue').Venue[];
  leagueVenues: import('./venue').LeagueVenue[];
  teams: TeamWithQueryDetails[];
  members: import('./member').PartialMember[]; // Partial members for captain/player selection
  seasonId: string | null;
  previousSeasonId: string | null;
  loading: boolean;
  error: string | null;
  refreshTeams: () => Promise<void>;
  // TODO: Remove this setter - use TanStack Query mutations/invalidations instead
  setTeams: React.Dispatch<React.SetStateAction<TeamWithQueryDetails[]>>;
}

/**
 * Utility function to check if roster is full
 */
export function isRosterFull(currentCount: number, rosterSize: number): boolean {
  return currentCount >= rosterSize;
}

/**
 * Utility function to get remaining roster spots
 */
export function getRemainingSpots(currentCount: number, rosterSize: number): number {
  return Math.max(0, rosterSize - currentCount);
}
