/**
 * @fileoverview Venue-related type definitions
 * Centralized types for venue management and configuration
 */

/**
 * Keys for table size categories
 * Used throughout the app to reference specific table size fields
 */
export type TableSizeKey = 'bar_box_tables' | 'eight_foot_tables' | 'regulation_tables';

/**
 * Table numbers grouped by size category
 * Used for custom table numbering configurations
 */
export type TableNumbers = {
  bar_box_tables: number[];
  eight_foot_tables: number[];
  regulation_tables: number[];
};


/**
 * Venue information interface
 * Represents a billiard hall/bar where matches can be played
 * Maps to the 'venues' table in the database
 *
 * Table Storage Model:
 * - Table numbers are stored in arrays by size (bar_box_table_numbers, etc.)
 * - Array length = count of tables of that size
 * - Array values = specific table numbers assigned to that size
 * - Legacy columns (bar_box_tables, regulation_tables) exist for backwards compatibility
 */
export interface Venue {
  id: string;
  organization_id: string | null; // Nullable: persists even if original organization deleted
  venue_owner_id: string | null;

  // Required fields
  name: string;
  street_address: string;
  city: string;
  state: string;
  zip_code: string;
  phone: string;

  // Legacy count columns (still in database for backwards compatibility)
  bar_box_tables: number; // 7ft tables count - use bar_box_table_numbers.length instead
  regulation_tables: number; // 9ft tables count - use regulation_table_numbers.length instead
  total_tables: number; // Computed: bar_box + regulation (database computed column)

  // Table number arrays - PRIMARY source of truth for table configuration
  // Array length = count, array values = specific table numbers
  // Example: bar_box_table_numbers = [1, 2, 3] means 3 bar box tables numbered 1, 2, 3
  bar_box_table_numbers: number[];
  eight_foot_table_numbers: number[];
  regulation_table_numbers: number[];

  // Optional contact info
  proprietor_name: string | null;
  proprietor_phone: string | null;
  league_contact_name: string | null;
  league_contact_phone: string | null;
  league_contact_email: string | null;
  website: string | null;

  // Optional operational details
  business_hours: string | null;
  notes: string | null;

  // Status
  is_active: boolean;

  // Metadata
  created_at: string;
  updated_at: string;
}

/**
 * Venue form data interface
 * Used during venue creation
 */
export interface VenueFormData {
  name: string;
  street_address: string;
  city: string;
  state: string;
  zip_code: string;
  phone: string;
  bar_box_tables: number;
  eight_foot_tables: number;
  regulation_tables: number;

  // Optional fields
  proprietor_name?: string;
  proprietor_phone?: string;
  league_contact_name?: string;
  league_contact_phone?: string;
  league_contact_email?: string;
  website?: string;
  business_hours?: string;
  notes?: string;
}

/**
 * League-Venue relationship
 * Maps to the 'league_venues' table in the database
 * Tracks which venues are available for a league and table limits
 */
export interface LeagueVenue {
  id: string;
  league_id: string;
  venue_id: string;

  // Array of specific table numbers available for this league
  // Example: [1, 2, 5, 6] - the table sizes are determined by venue's table_configuration
  available_table_numbers: number[];

  // Maximum number of home teams that can use this venue
  // Can be set lower than the number of available tables for scheduling flexibility
  // NULL means unlimited (defaults to available table count)
  capacity: number | null;

  // Metadata
  added_at: string;
  updated_at: string;
}

/**
 * Data for inserting league-venue relationship
 * Uses Omit<> to exclude auto-generated fields and calculated stats
 * This automatically stays in sync when LeagueVenue type changes
 */
export type LeagueVenueInsertData = Omit<LeagueVenue,
  | 'id'                          // Auto-generated by database
  | 'added_at'                    // Auto-generated timestamp
  | 'updated_at'                  // Auto-generated timestamp
>;

/**
 * Data for inserting new venue
 * Uses Omit<> to exclude auto-generated fields and calculated stats
 * This automatically stays in sync when Venue type changes
 *
 * Note: We exclude the legacy count columns (bar_box_tables, regulation_tables)
 * because the new array columns are the source of truth.
 */
export type VenueInsertData = Omit<Venue,
  | 'id'                  // Auto-generated by database
  | 'venue_owner_id'      // Set separately after venue creation
  | 'bar_box_tables'      // Legacy count column - use array length instead
  | 'regulation_tables'   // Legacy count column - use array length instead
  | 'total_tables'        // Computed field (bar_box + regulation)
  | 'is_active'           // Has default value in database
  | 'created_at'          // Auto-generated timestamp
  | 'updated_at'          // Auto-generated timestamp
>;
