-- Migration: Disable ALL RLS for development
-- Disables RLS on all tables to prevent blocking during development
-- RE-ENABLE AND FIX POLICIES BEFORE PRODUCTION DEPLOYMENT!

BEGIN;

-- Core tables
ALTER TABLE IF EXISTS organizations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS organization_staff DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS members DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS leagues DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS seasons DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS season_weeks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS teams DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS venues DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS league_venues DISABLE ROW LEVEL SECURITY;

-- Match/game tables
ALTER TABLE IF EXISTS matches DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS match_lineups DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS match_games DISABLE ROW LEVEL SECURITY;

-- Player/roster tables
ALTER TABLE IF EXISTS players DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS player_season_stats DISABLE ROW LEVEL SECURITY;

-- Preference/configuration tables
ALTER TABLE IF EXISTS operator_blackout_preferences DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS championship_date_options DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS preferences DISABLE ROW LEVEL SECURITY;

-- Messaging tables
ALTER TABLE IF EXISTS conversations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS conversation_participants DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS blocked_users DISABLE ROW LEVEL SECURITY;

-- Reporting/moderation tables
ALTER TABLE IF EXISTS user_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS report_updates DISABLE ROW LEVEL SECURITY;

COMMIT;

-- Note: This disables ALL security for development
-- You MUST re-enable and properly configure RLS before production!
